import React from "react";
import { Inter } from "next/font/google";
import "./firebase/initFirebase";
import "./globals.css";
import { Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { session } from "./session";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Image Generator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
